apiVersion: vi 
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: meunginx
spec: 
  replicas: 3
  selector:
    matchLabels: 
      app: meunginx
  template: 
    metadata:
      labels:
        app: meunginx
    spec: 
      containers: 
      - name: webserver
        image: nginx:1.14.2
        ports:
        - containerPort: 80